export const SET_MOVEMENT = "SET_MOVEMENT";

export const SET_THEME_TOGGLE = "SET_THEME_TOGGLE";

export const SET_SHOW_ONBOARDING = "SET_SHOW_ONBOARDING";
export const SET_HIDE_ONBOARDING = "SET_HIDE_ONBOARDING";
