export type trainingType = "fullBody" | "chestBackBiceps" | "shoulderTricepsLegs";

export type movementType =
  | "chestPress"
  | "butterfly"
  | "shoulderPress"
  | "latPulldown"
  | "lowRow"
  | "dumbellCurls"
  | "scottCurl"
  | "pushDown"
  | "squat"
  | "benchPress"
  | "inlineBenchPress"
  | "dumbellPullRow"
  | "dumbellRow"
  | "zBarBarbellCurl"
  | "inclineDumbellCurl"
  | "wrist"
  | "lateralPress"
  | "bentOverRaise"
  | "uprightRow"
  | "zBarLying"
  | "dumbellTriceps"
  | "legsExtension"
  | "legsCurl";
